apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluxprod-tsb
spec:
  interval: 1m
  url: https://shamusx.github.io/bookish-system
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluxprod-tsb
spec:
  interval: 5m
  prune: true
  path: ./tsb-mp/prod
  sourceRef:
    kind: GitRepository
    name: fluxprod-tsb