apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluxprod-tsb
spec:
  interval: 1m
  url: https://github.com/shamusx/bookish-system
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluxprod-tsb
spec:
  interval: 5m
  prune: true
  path: ./clusters/app-clusters/httpbin
  sourceRef:
    kind: GitRepository
    name: fluxprod-tsb