apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-app-bookish
  namespace: flux-app-config
spec:
  interval: 1m
  url: https://github.com/shamusx/bookish-system
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-httpbin-bookish
  namespace: flux-app-config
spec:
  interval: 5m
  prune: true
  path: ./applications/httpbin
  sourceRef:
    kind: GitRepository
    name: flux-app-bookish